### ISSUE TITLE
[Bug] Bug with onChange JS feature on text and number input fields

### ISSUE THREAD

**Issue by PatoFb** [updivision/material-dashboard-laravel#31] opened 2021-05-19 21:20 UTC
### Version
1.0.8
### Reproduction link
https://github.com/PatoFb/cotizadortunalitec
### Operating System
Windows
### Device
Laptop Lenovo Legion
### Browser & Version
Google Chrome Version 90.0.4430.212
### Steps to reproduce
•	Install composer https://getcomposer.org/download/
•	I am using XAMPP with MySql so you can install that as wel
•	Clone the repository: git clone https://github.com/PatoFb/cotizadortunalitec.git (everything is in the develop branch)
•	Run composer update in terminal.
•	Run npm install.
•	Rename .env.example file to .env
•	Fill your MySQL configuration.
•	Create your empty database in MySQL.
•	In terminal, run php artisan migrate to create the tables.
•	php artisan storage:links to link the storage disk to the public directory
•	To execute the program, run php artisan serve in your terminal and in your web browser go to http://127.0.0.1:8000/.
•	Click on Registrarse (top corner).
•	Fill all the data, everything is required.
•	Create a role named "Admin" with id 1 directly from localhost/phpMyAdmin
•	Once logged in click on every option in the Admin side menu in the sidebar and make at least one object of each
•	Click in Crear Orden
•	In tipos de productos create one named "Cortinas"
•	Click in Crear Orden
•	Fill the form and click the button
•	Select "Cortinas" and click "Siguiente"
•	Modify the values of "Ancho" and/or "Caída"

### What is expected?
The request should be called just once on change
### What is actually happening?
The change event triggers infinitely

---
### Additional comments
I tried a lot of stuff and came to the conclusion that it is probably related to the bootstrap-material-design.min.js

**Comment by teamupdivision** [comment] 2021-05-24 15:35
Hi @PatoFb,

Thank you for reporting this issue and for using Creative Tim products.
 
Could you please send a few more details to us? We were not able to reproduce the error. Also, if you can share with us its behavior in the demo, it will help a lot in investigating this further.
 
All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-06-09 05:52
Hi @PatoFb,

We would like to check if the issue was solved or if you can share a few more details on the steps followed. Please let us know if there is anything else we can help with and if you have any other issues.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-07-07 11:22
Hi there @PatoFb, 

We would like to check if the issue was solved and if there is anything else we can help with. 
Please let us know if you have any other issues. 

All the best,
Updivision Team

**Comment by PatoFb** [comment] 2021-07-07 17:04
Hello @teamupdivision and sorry for the late response. I could't resolve the onchange issue and definitely found out it was something with the minified file. I used oninput instead and worked perfectly, but not sure if that has to be adressed.

**Comment by teamupdivision** [comment] 2021-07-15 14:53
Hi @PatoFb,

Thank you for letting us know and we're glad the solution worked. We checked on our side and it looks like this couldn't be reproduced so we assume it may be related to the later edits. In case there is anything else or if you have any other issues please let us know. 

All the best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-07-22 13:43
Hi @PatoFb,
 
We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know. Thank you. 

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Closed as completed by teamupdivision** 2021-07-22 13:43 UTC
